apiVersion: v1
kind: Service
metadata:
  labels:
    app: temporal-flight-booking-worker
  name: metrics
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: grpc
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: temporal-flight-booking-worker
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}