apiVersion: v1
kind: Service
metadata:
  labels:
    app: temporal-flight-booking-worker
    app.kubernetes.io/headless: "true"
    app.kubernetes.io/instance: benchtest-regular
    app.kubernetes.io/name: metrics-monitor   
  name: metrics
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: grpc
    port: 9000
    protocol: TCP
    targetPort: grpc  
  selector:
    app: temporal-flight-booking-worker
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}