apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-flight-booking-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: temporal-flight-booking-ui
  template:
    metadata:
      labels:
        app: temporal-flight-booking-ui
    spec:
      containers:
      - name: workflow
        image: ktenzer/temporal-flight-booking-workflow:v1.4
        imagePullPolicy: Always
        ports:
        - name: workflow
          containerPort: 5000
        env:
        - name: TEMPORAL_HOST_URL
          value: temporal-booking.sdvdw.tmprl.cloud:7233
        - name: TEMPORAL_NAMESPACE
          value: temporal-booking.sdvdw
        - name: TEMPORAL_TASK_QUEUE
          value: temporal-flight-booking
        - name: TEMPORAL_MTLS_TLS_CERT
          value: /etc/certs/tls.crt
        - name: TEMPORAL_MTLS_TLS_KEY
          value: /etc/certs/tls.key
        volumeMounts:
        - mountPath: /etc/certs
          name: certs
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          secretName: temporal-flight-booking-tls
